### ISSUE TITLE
Center the navigation buttons in the navbar

### ISSUE THREAD

**Issue by LukasMFR** [LukasMFR/projet-php-e-commerce#12]
### Current state
![Capture d’écran 2024-04-05 à 22 42 47](https://github.com/LukasMFR/projet-php-e-commerce/assets/41242166/7f5f34a5-e1e0-4a54-8bca-4c27e98080ad)

Three tabs are opened and the website is in the middle, and we can clearly see that the buttons are not centered. Make sure to not mess up with .flex

**Comment by LukasMFR** [comment]
Code idea:

```css
.header .flex {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 1rem;
  height: 70px;
}

.brand-navbar {
  flex: 1;
  display: flex;
  justify-content: flex-start; /* Align brand to the left */
}

.navbar {
  flex: 2;
  display: flex;
  justify-content: center; /* Center navbar links */
  margin: 0; /* Remove margin to use padding for spacing */
  padding: 0 2rem; /* Use padding to prevent overlap */
}

.icons {
  flex: 1;
  display: flex;
  justify-content: flex-end; /* Align icons to the right */
}
```

Sadly this code adds like margins when the window size is smaller.
